services:
  psql:
    container_name: psql
    hostname: psql
    image: postgres:18
    restart: 'no'
    volumes:
      # ‚ö†Ô∏è IMPORTANTE: Estou em src/examples/ex010/.
      # ‚ö†Ô∏è IMPORTANTE: Todas as pastas _local_data precisam estar no .gitignore.
      # ‚ÑπÔ∏è INFO: Isso vai gerar a pasta src/examples/ex010/_local_data no projeto
      # üÜò docker-compose -f src/examples/ex010/compose.yml up
      - ./_local_data/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    env_file: "../../../.env"